package postgres

var usersTableColumns = []string{
	"userid",
	"password",
	"salt",
	"email",
	"emailverified",
	"firstname",
	"lastname",
	"url",
	"birthday",
	"gender",
	"firstcontactat",
	"serviceversion1userseq",
	"ispublic",
	"followingleagues",
	"physical",
	"updatedat",
	"namepattern",
	"follower",
	"teams",
	"leagues",
	"devices",
	"lastlocation",
	"isserviceversion1",
	"followingpendingteams",
	"following",
	"isprivateaccount",
	"name",
	"favorsports",
	"followingteams",
	"serviceversion1password",
	"facebookid",
	"picture",
	"loginid",
	"lasttimetoviewfeed",
	"facebook",
	"signupsourceip",
	"signupuseragent",
	"provider_type",
	"googleid",
	"google",
	"usertimezone",
	"livesin",
	"teamsasfamily",
	"pendingteamstojoinbyteamrequest",
	"pendingteamstojoinbyemail",
	"pendingteamstojoinbymyrequest",
	"followpendingusers",
	"phonenumber",
	"countrycode",
	"birthplace",
	"pending",
	"customerid",
	"disconnectedaccounts",
	"followpendingteams",
	"followpendingleagues",
	"accountid",
	"locale",
	"hiddenparties",
	"usedparties",
	"pendingteamsasfamily",
	"country",
	"deleted",
	"pages",
	"createdat",
}

var teamsTableColumns = []string{
	"timezone",
	"type",
	"creatorsrole",
	"createdat",
	"displaystat",
	"ispublic",
	"id",
	"updatedat",
	"seasons",
	"follower",
	"sports",
	"lastlocation",
	"canwrite",
	"agegroup",
	"families",
	"url",
	"picture",
	"coaches",
	"deleted",
	"rosters",
	"createdby",
	"isprivateaccount",
	"name",
	"defaultpicture",
	"location",
	"admins",
	"desc",
	"scorekeeper",
	"foundedin",
	"leagues",
	"isserviceversion1",
	"abbreviation",
	"serviceversion1teamseq",
	"pendingleaguesfromrequest",
	"pendingrostersfromteamrequest",
	"pendingrostersfromrequest",
	"coach",
	"homefield",
	"updatedby",
	"pendingfamilies",
	"pendingfollow",
	"crawled",
	"notjoinedfamilyemails",
}

var gamesTableColumns = []string{
	"ownertype",
	"gametype",
	"timezone",
	"ownerid",
	"title",
	"photos",
	"createdat",
	"serviceversion1gameseq",
	"islocationtbd",
	"ispublic",
	"id",
	"startat",
	"postponed",
	"pushnotification",
	"comments",
	"sports",
	"hasend",
	"going",
	"lastlocation",
	"isserviceversion1",
	"coachcomments",
	"deleted",
	"createdby",
	"locationdetails",
	"cancelled",
	"location",
	"notgoing",
	"maybe",
	"description",
	"allowrsvpdeadline",
	"participantlimit",
	"updatedat",
	"updatedby",
	"crawled",
	"allowguestlimit",
	"photo",
	"endat",
	"allowparticipantlimit",
	"rsvpdeadline",
	"limitguestperparticipant",
	"guests",
	"allowguest",
	"hometeamgoing",
	"awayteam",
	"matchtype",
	"ownerteamtype",
	"division",
	"season",
	"hometeam",
	"awayteamgoing",
	"fee",
	"detailfee",
	"gender",
	"skilllevel",
	"fieldtype",
	"result",
	"resulttype",
	"arriveearly",
	"invited",
	"awayteamnotgoing",
	"hometeamnotgoing",
	"hometeammaybe",
	"awayteammaybe",
	"uniform",
	"esulttype",
}

var paymentTableColumns = []string{
	"recipientuserid",
	"accountid",
	"createdat",
	"charge",
	"meta",
	"id",
	"title",
	"userid",
	"status",
	"refund",
}

func getUsersTableColumns() []string {
	return usersTableColumns
}

func getTeamsTableColumns() []string {
	return teamsTableColumns
}

func getGamesTableColumns() []string {
	return gamesTableColumns
}

func getPaymentTableColumns() []string {
	return paymentTableColumns
}
